Added initV scripts and modified setup to install in correct location

diff --git a/etc/ch-sf b/etc/ch-sf
--- a/etc/ch-sf
+++ b/etc/ch-sf
@@ -1,47 +1,182 @@
 #! /bin/sh
-# /etc/init.d/ch-sf
-
 ### BEGIN INIT INFO
 # Provides:          ch-sf
-# Required-Start:    $remote_fs $syslog mysql
-# Required-Stop:     $remote_fs $syslog mysql
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Serial Forwarder
-# Description:       A simple script from www.stuffaboutcode.com which will start / stop cogent-house at boot / shutdown.
+# Short-Description: TinyOS Serial Forwarder
+# Description:       Start / Stop Serial Forwder for TinyOS PC <-> Mote Communications
 ### END INIT INFO
 
+# Author: Daniel Goldsmith <djgoldsmith@googlemail.com>
+
+# Do NOT "set -e"
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="TinyOS Serial Forwarder"
+NAME=ch-sf
+DAEMON=/usr/bin/java
+DAEMON_ARGS="net.tinyos.sf.SerialForwarder -no-output -comm serial@/dev/ttyUSB0:telosb"
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
+
+
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
 . /lib/lsb/init-functions
 
-case "$1" in
-    start)
-	log_daemon_msg "Starting cogent-house serial forwarder" "ch-sf" || true
-	. /opt/tinyos-main-read-only/tinyos.sh>/dev/null
 
-	PORT="/dev/ttyTelos"
-	if start-stop-daemon --start --background --make-pidfile --chuid chuser --oknodo --pidfile /var/run/ch-sf.pid --exec /usr/bin/java -- net.tinyos.sf.SerialForwarder -comm serial@$PORT:telosb -no-output; then
-	    log_end_msg 0 || true
-	else
-	    log_end_msg 1 || true
-	fi
+#Override Verbose Setting
+VERBOSE="yes"
+
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+
+        #We need to source the tinyos stuff
+    export TOSROOT="/opt/tinyos-2.1.2/"
+    export TOSDIR="$TOSROOT/tos"
+    export CLASSPATH=$CLASSPATH:$TOSROOT/support/sdk/java/tinyos.jar
+    export MAKERULES="$TOSROOT/support/make/Makerules"
+    export PYTHONPATH=$PYTHONPATH:$TOSROOT/support/sdk/python
+    export VIRTUAL_ENV="TinyOS"
+
+
+# Extend path for java
+    type java >/dev/null 2>/dev/null || PATH=`/usr/bin/tos-locate-jre --java`:$PATH
+    type javac >/dev/null 2>/dev/null || PATH=`/usr/bin/tos-locate-jre --javac`:$PATH
+#echo $PATH | grep -q /usr/bin ||  PATH=/usr/bin:$PATH
+
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+		|| return 1
+	#start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+	start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- \
+		$DAEMON_ARGS \
+		|| return 2
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+
+	#   other if a failure occurred
+        
+
+	#start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+        start-stop-daemon --stop --quiet --retry=INT/30/KILL/5 --pidfile $PIDFILE
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	return 0
+}
+
+case "$1" in
+  start)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
-    stop)
-	log_daemon_msg "Stopping cogent-house serial forwarder" "ch-sf" || true
-    # kill application you want to stop
-	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/ch-sf.pid; then
-	    log_end_msg 0 || true
-	else
-	    log_end_msg 1 || true
-	fi
+  stop)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
-    status)
-	status_of_proc -p /var/run/ch-sf.pid /usr/bin/java ch-sf && exit 0 || exit $?
+  status)
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
 	;;
-    
-    *)
-	log_action_msg "Usage: /etc/init.d/ch-sf {start|stop}" || true
-	exit 1
+  #reload|force-reload)
+	#
+	# If do_reload() is not implemented then leave this commented out
+	# and leave 'force-reload' as an alias for 'restart'.
+	#
+	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#do_reload
+	#log_end_msg $?
+	#;;
+  restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+		# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
+  *)
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
 	;;
 esac
 
-exit 0
+:
